export const stationList = [
  { name: "Abbey Road DLR Station", id: "940GZZDLABR", zone: "2+3" },
  { name: "Acton Central Rail Station", id: "910GACTNCTL", zone: "3" },
  { name: "Acton Main Line Rail Station", id: "910GACTONML", zone: "3" },
  { name: "Acton Town Underground Station", id: "940GZZLUACT", zone: "3" },
  { name: "Aldgate East Underground Station", id: "940GZZLUADE", zone: "1" },
  { name: "Aldgate Underground Station", id: "940GZZLUALD", zone: "1" },
  { name: "All Saints DLR Station", id: "940GZZDLALL", zone: "2" },
  { name: "Alperton Underground Station", id: "940GZZLUALP", zone: "4" },
  { name: "Amersham Underground Station", id: "940GZZLUAMS", zone: "9" },
  { name: "Anerley Rail Station", id: "910GANERLEY", zone: "4" },
  { name: "Angel Underground Station", id: "940GZZLUAGL", zone: "1" },
  { name: "Archway Underground Station", id: "940GZZLUACY", zone: "2+3" },
  { name: "Arnos Grove Underground Station", id: "940GZZLUASG", zone: "4" },
  { name: "Arsenal Underground Station", id: "940GZZLUASL", zone: "2" },
  { name: "Baker Street Underground Station", id: "940GZZLUBST", zone: "1" },
  { name: "Balham Underground Station", id: "940GZZLUBLM", zone: "3" },
  { name: "Bank DLR Station", id: "940GZZDLBNK", zone: "1" },
  { name: "Bank Underground Station", id: "940GZZLUBNK", zone: "1" },
  { name: "Barbican Underground Station", id: "940GZZLUBBN", zone: "1" },
  { name: "Barking Rail Station", id: "910GBARKING", zone: "4" },
  { name: "Barking Underground Station", id: "940GZZLUBKG", zone: "4" },
  { name: "Barkingside Underground Station", id: "940GZZLUBKE", zone: "4" },
  { name: "Barons Court Underground Station", id: "940GZZLUBSC", zone: "2" },
  { name: "Bayswater Underground Station", id: "940GZZLUBWT", zone: "1" },
  { name: "Beckton DLR Station", id: "940GZZDLBEC", zone: "3" },
  { name: "Beckton Park DLR Station", id: "940GZZDLBPK", zone: "3" },
  { name: "Becontree Underground Station", id: "940GZZLUBEC", zone: "5" },
  { name: "Belsize Park Underground Station", id: "940GZZLUBZP", zone: "2" },
  { name: "Bermondsey Underground Station", id: "940GZZLUBMY", zone: "2" },
  { name: "Bethnal Green Rail Station", id: "910GBTHNLGR", zone: "2" },
  { name: "Bethnal Green Underground Station", id: "940GZZLUBLG", zone: "2" },
  { name: "Blackfriars Underground Station", id: "940GZZLUBKF", zone: "1" },
  { name: "Blackhorse Road Rail Station", id: "910GBLCHSRD", zone: "3" },
  { name: "Blackhorse Road Underground Station", id: "940GZZLUBLR", zone: "3" },
  { name: "Blackwall DLR Station", id: "940GZZDLBLA", zone: "2" },
  { name: "Bond Street Underground Station", id: "940GZZLUBND", zone: "1" },
  { name: "Borough Underground Station", id: "940GZZLUBOR", zone: "1" },
  { name: "Boston Manor Underground Station", id: "940GZZLUBOS", zone: "4" },
  { name: "Bounds Green Underground Station", id: "940GZZLUBDS", zone: "3+4" },
  { name: "Bow Church DLR Station", id: "940GZZDLBOW", zone: "2" },
  { name: "Bow Road Underground Station", id: "940GZZLUBWR", zone: "2" },
  { name: "Brent Cross Underground Station", id: "940GZZLUBTX", zone: "3" },
  { name: "Brentwood Rail Station", id: "910GBRTWOOD", zone: "9" },
  { name: "Brixton Underground Station", id: "940GZZLUBXN", zone: "2" },
  { name: "Brockley Rail Station", id: "910GBROCKLY", zone: "2" },
  {
    name: "Bromley-by-Bow Underground Station",
    id: "940GZZLUBBB",
    zone: "2+3"
  },
  { name: "Brondesbury Park Rail Station", id: "910GBRBYPK", zone: "2" },
  { name: "Brondesbury Rail Station", id: "910GBRBY", zone: "2" },
  { name: "Bruce Grove Rail Station", id: "910GBRUCGRV", zone: "3" },
  { name: "Buckhurst Hill Underground Station", id: "940GZZLUBKH", zone: "5" },
  { name: "Burnt Oak Underground Station", id: "940GZZLUBTK", zone: "4" },
  { name: "Bush Hill Park Rail Station", id: "910GBHILLPK", zone: "5" },
  { name: "Bushey Rail Station", id: "910GBUSHYDC", zone: "8" },
  {
    name: "Caledonian Road & Barnsbury Rail Station",
    id: "910GCLDNNRB",
    zone: "2"
  },
  { name: "Caledonian Road Underground Station", id: "940GZZLUCAR", zone: "2" },
  {
    name: "Cambridge Heath (London) Rail Station",
    id: "910GCAMHTH",
    zone: "2"
  },
  { name: "Camden Road Rail Station", id: "910GCMDNRD", zone: "2" },
  { name: "Camden Town Underground Station", id: "940GZZLUCTN", zone: "2" },
  { name: "Canada Water Rail Station", id: "910GCNDAW", zone: "2" },
  { name: "Canada Water Underground Station", id: "940GZZLUCWR", zone: "2" },
  { name: "Canary Wharf DLR Station", id: "940GZZDLCAN", zone: "2" },
  { name: "Canary Wharf Underground Station", id: "940GZZLUCYF", zone: "2" },
  { name: "Canning Town DLR Station", id: "940GZZDLCGT", zone: "2+3" },
  { name: "Canning Town Underground Station", id: "940GZZLUCGT", zone: "2+3" },
  { name: "Cannon Street Underground Station", id: "940GZZLUCST", zone: "1" },
  { name: "Canonbury Rail Station", id: "910GCNNB", zone: "2" },
  { name: "Canons Park Underground Station", id: "940GZZLUCPK", zone: "5" },
  { name: "Carpenders Park Rail Station", id: "910GCRPNDPK", zone: "7" },
  { name: "Chadwell Heath Rail Station", id: "910GCHDWLHT", zone: "5" },
  {
    name: "Chalfont & Latimer Underground Station",
    id: "940GZZLUCAL",
    zone: "8"
  },
  { name: "Chalk Farm Underground Station", id: "940GZZLUCFM", zone: "2" },
  { name: "Chancery Lane Underground Station", id: "940GZZLUCHL", zone: "1" },
  { name: "Charing Cross Underground Station", id: "940GZZLUCHX", zone: "1" },
  { name: "Chesham Underground Station", id: "940GZZLUCSM", zone: "9" },
  { name: "Cheshunt Rail Station", id: "910GCHESHNT", zone: "8" },
  { name: "Chigwell Underground Station", id: "940GZZLUCWL", zone: "4" },
  { name: "Chingford Rail Station", id: "910GCHINGFD", zone: "5" },
  { name: "Chiswick Park Underground Station", id: "940GZZLUCWP", zone: "3" },
  { name: "Chorleywood Underground Station", id: "940GZZLUCYD", zone: "7" },
  { name: "Clapham Common Underground Station", id: "940GZZLUCPC", zone: "2" },
  { name: "Clapham High Street Rail Station", id: "910GCLPHHS", zone: "2" },
  { name: "Clapham Junction Station", id: "910GCLPHMJ1", zone: "2" },
  { name: "Clapham North Underground Station", id: "940GZZLUCPN", zone: "2" },
  { name: "Clapham South Underground Station", id: "940GZZLUCPS", zone: "2+3" },
  { name: "Clapton Rail Station", id: "910GCLAPTON", zone: "2+3" },
  { name: "Cockfosters Underground Station", id: "940GZZLUCKS", zone: "5" },
  { name: "Colindale Underground Station", id: "940GZZLUCND", zone: "4" },
  { name: "Colliers Wood Underground Station", id: "940GZZLUCSD", zone: "3" },
  { name: "Covent Garden Underground Station", id: "940GZZLUCGN", zone: "1" },
  { name: "Crossharbour DLR Station", id: "940GZZDLCLA", zone: "2" },
  { name: "Crouch Hill Rail Station", id: "910GCROUCHH", zone: "3" },
  { name: "Croxley Underground Station", id: "940GZZLUCXY", zone: "7" },
  { name: "Crystal Palace Rail Station", id: "910GCRYSTLP", zone: "3+4" },
  {
    name: "Custom House (for ExCel) DLR Station",
    id: "940GZZDLCUS",
    zone: "3"
  },
  {
    name: "Cutty Sark (for Maritime Greenwich) DLR Station",
    id: "940GZZDLCUT",
    zone: "2+3"
  },
  { name: "Cyprus DLR Station", id: "940GZZDLCYP", zone: "3" },
  { name: "Dagenham East Underground Station", id: "940GZZLUDGE", zone: "5" },
  {
    name: "Dagenham Heathway Underground Station",
    id: "940GZZLUDGY",
    zone: "5"
  },
  { name: "Dalston Junction Rail Station", id: "910GDALS", zone: "2" },
  { name: "Dalston Kingsland Rail Station", id: "910GDALSKLD", zone: "2" },
  { name: "Debden Underground Station", id: "940GZZLUDBN", zone: "6" },
  { name: "Denmark Hill Rail Station", id: "910GDENMRKH", zone: "2" },
  { name: "Deptford Bridge DLR Station", id: "940GZZDLDEP", zone: "2+3" },
  { name: "Devons Road DLR Station", id: "940GZZDLDEV", zone: "2" },
  { name: "Dollis Hill Underground Station", id: "940GZZLUDOH", zone: "3" },
  { name: "Ealing Broadway Rail Station", id: "910GEALINGB", zone: "3" },
  { name: "Ealing Broadway Underground Station", id: "940GZZLUEBY", zone: "3" },
  { name: "Ealing Common Underground Station", id: "940GZZLUECM", zone: "3" },
  { name: "Earl's Court Underground Station", id: "940GZZLUECT", zone: "1+2" },
  { name: "East Acton Underground Station", id: "940GZZLUEAN", zone: "2" },
  { name: "East Finchley Underground Station", id: "940GZZLUEFY", zone: "3" },
  { name: "East Ham Underground Station", id: "940GZZLUEHM", zone: "3+4" },
  { name: "East India DLR Station", id: "940GZZDLEIN", zone: "2+3" },
  { name: "East Putney Underground Station", id: "940GZZLUEPY", zone: "2+3" },
  { name: "Eastcote Underground Station", id: "940GZZLUEAE", zone: "5" },
  {
    name: "Edgware Road (Bakerloo) Underground Station",
    id: "940GZZLUERB",
    zone: "1"
  },
  {
    name: "Edgware Road (Circle Line) Underground Station",
    id: "940GZZLUERC",
    zone: "1"
  },
  { name: "Edgware Underground Station", id: "940GZZLUEGW", zone: "5" },
  { name: "Edmonton Green Rail Station", id: "910GEDMNGRN", zone: "4" },
  {
    name: "Elephant & Castle Underground Station",
    id: "940GZZLUEAC",
    zone: "1+2"
  },
  { name: "Elm Park Underground Station", id: "940GZZLUEPK", zone: "6" },
  { name: "Elverson Road DLR Station", id: "940GZZDLELV", zone: "2+3" },
  { name: "Embankment Underground Station", id: "940GZZLUEMB", zone: "1" },
  { name: "Emerson Park Rail Station", id: "910GEMRSPKH", zone: "6" },
  { name: "Enfield Town Rail Station", id: "910GENFLDTN", zone: "5" },
  { name: "Epping Underground Station", id: "940GZZLUEPG", zone: "6" },
  { name: "Euston Square Underground Station", id: "940GZZLUESQ", zone: "1" },
  { name: "Euston Underground Station", id: "940GZZLUEUS", zone: "1" },
  { name: "Fairlop Underground Station", id: "940GZZLUFLP", zone: "4" },
  { name: "Farringdon Underground Station", id: "940GZZLUFCN", zone: "1" },
  {
    name: "Finchley Central Underground Station",
    id: "940GZZLUFYC",
    zone: "4"
  },
  {
    name: "Finchley Road & Frognal Rail Station",
    id: "910GFNCHLYR",
    zone: "2"
  },
  { name: "Finchley Road Underground Station", id: "940GZZLUFYR", zone: "2" },
  { name: "Finsbury Park Underground Station", id: "940GZZLUFPK", zone: "2" },
  { name: "Forest Gate Rail Station", id: "910GFRSTGT", zone: "3" },
  { name: "Forest Hill Rail Station", id: "910GFORESTH", zone: "3" },
  { name: "Fulham Broadway Underground Station", id: "940GZZLUFBY", zone: "2" },
  { name: "Gallions Reach DLR Station", id: "940GZZDLGAL", zone: "3" },
  { name: "Gants Hill Underground Station", id: "940GZZLUGTH", zone: "4" },
  { name: "Gidea Park Rail Station", id: "910GGIDEAPK", zone: "6" },
  { name: "Gloucester Road Underground Station", id: "940GZZLUGTR", zone: "1" },
  { name: "Golders Green Underground Station", id: "940GZZLUGGN", zone: "3" },
  { name: "Goldhawk Road Underground Station", id: "940GZZLUGHK", zone: "2" },
  { name: "Goodge Street Underground Station", id: "940GZZLUGDG", zone: "1" },
  { name: "Goodmayes Rail Station", id: "910GGODMAYS", zone: "4" },
  { name: "Gospel Oak Rail Station", id: "910GGOSPLOK", zone: "2" },
  { name: "Grange Hill Underground Station", id: "940GZZLUGGH", zone: "4" },
  {
    name: "Great Portland Street Underground Station",
    id: "940GZZLUGPS",
    zone: "1"
  },
  { name: "Green Park Underground Station", id: "940GZZLUGPK", zone: "1" },
  { name: "Greenford Underground Station", id: "940GZZLUGFD", zone: "4" },
  { name: "Greenwich DLR Station", id: "940GZZDLGRE", zone: "2+3" },
  { name: "Gunnersbury Rail Station", id: "910GGNRSBRY", zone: "3" },
  { name: "Gunnersbury Underground Station", id: "940GZZLUGBY", zone: "3" },
  { name: "Hackney Central Rail Station", id: "910GHACKNYC", zone: "2" },
  { name: "Hackney Downs Rail Station", id: "910GHAKNYNM", zone: "2" },
  { name: "Hackney Wick Rail Station", id: "910GHACKNYW", zone: "2" },
  { name: "Haggerston Rail Station", id: "910GHAGGERS", zone: "2" },
  { name: "Hainault Underground Station", id: "940GZZLUHLT", zone: "4" },
  {
    name: "Hammersmith (Dist&Picc Line) Underground Station",
    id: "940GZZLUHSD",
    zone: "2"
  },
  {
    name: "Hammersmith (H&C Line) Underground Station",
    id: "940GZZLUHSC",
    zone: "2"
  },
  { name: "Hampstead Heath Rail Station", id: "910GHMPSTDH", zone: "2" },
  { name: "Hampstead Underground Station", id: "940GZZLUHTD", zone: "2+3" },
  { name: "Hanger Lane Underground Station", id: "940GZZLUHGR", zone: "3" },
  { name: "Hanwell Rail Station", id: "910GHANWELL", zone: "4" },
  { name: "Harlesden Rail Station", id: "910GHARLSDN", zone: "3" },
  { name: "Harlesden Underground Station", id: "940GZZLUHSN", zone: "3" },
  { name: "Harold Wood Rail Station", id: "910GHRLDWOD", zone: "6" },
  { name: "Harringay Green Lanes Rail Station", id: "910GHRGYGL", zone: "3" },
  { name: "Harrow & Wealdstone Rail Station", id: "910GHROW", zone: "5" },
  {
    name: "Harrow & Wealdstone Underground Station",
    id: "940GZZLUHAW",
    zone: "5"
  },
  {
    name: "Harrow-on-the-Hill Underground Station",
    id: "940GZZLUHOH",
    zone: "5"
  },
  { name: "Hatch End Rail Station", id: "910GHTCHEND", zone: "6" },
  { name: "Hatton Cross Underground Station", id: "940GZZLUHNX", zone: "5+6" },
  { name: "Hayes & Harlington Rail Station", id: "910GHAYESAH", zone: "5" },
  { name: "Headstone Lane Rail Station", id: "910GHEDSTNL", zone: "5" },
  { name: "Heathrow Terminal 4 Rail Station", id: "910GHTRWTM4", zone: "6" },
  {
    name: "Heathrow Terminal 4 Underground Station",
    id: "940GZZLUHR4",
    zone: "6"
  },
  {
    name: "Heathrow Terminal 5 Underground Station",
    id: "940GZZLUHR5",
    zone: "6"
  },
  {
    name: "Heathrow Terminals 2 & 3 Rail Station",
    id: "910GHTRWAPT",
    zone: "6"
  },
  {
    name: "Heathrow Terminals 2 & 3 Underground Station",
    id: "940GZZLUHRC",
    zone: "6"
  },
  {
    name: "Hendon Central Underground Station",
    id: "940GZZLUHCL",
    zone: "3+4"
  },
  { name: "Heron Quays DLR Station", id: "940GZZDLHEQ", zone: "2" },
  { name: "High Barnet Underground Station", id: "940GZZLUHBT", zone: "5" },
  {
    name: "High Street Kensington Underground Station",
    id: "940GZZLUHSK",
    zone: "1"
  },
  { name: "Highams Park Rail Station", id: "910GHGHMSPK", zone: "4" },
  { name: "Highbury & Islington Rail Station", id: "910GHGHI", zone: "2" },
  {
    name: "Highbury & Islington Underground Station",
    id: "940GZZLUHAI",
    zone: "2"
  },
  { name: "Highgate Underground Station", id: "940GZZLUHGT", zone: "3" },
  { name: "Hillingdon Underground Station", id: "940GZZLUHGD", zone: "6" },
  { name: "Holborn Underground Station", id: "940GZZLUHBN", zone: "1" },
  { name: "Holland Park Underground Station", id: "940GZZLUHPK", zone: "2" },
  { name: "Holloway Road Underground Station", id: "940GZZLUHWY", zone: "2" },
  { name: "Homerton Rail Station", id: "910GHOMRTON", zone: "2" },
  { name: "Honor Oak Park Rail Station", id: "910GHONROPK", zone: "3" },
  { name: "Hornchurch Underground Station", id: "940GZZLUHCH", zone: "6" },
  {
    name: "Hounslow Central Underground Station",
    id: "940GZZLUHWC",
    zone: "4"
  },
  { name: "Hounslow East Underground Station", id: "940GZZLUHWE", zone: "4" },
  { name: "Hounslow West Underground Station", id: "940GZZLUHWT", zone: "5" },
  { name: "Hoxton Rail Station", id: "910GHOXTON", zone: "1+2" },
  {
    name: "Hyde Park Corner Underground Station",
    id: "940GZZLUHPC",
    zone: "1"
  },
  { name: "Ickenham Underground Station", id: "940GZZLUICK", zone: "6" },
  { name: "Ilford Rail Station", id: "910GILFORD", zone: "4" },
  { name: "Imperial Wharf Rail Station", id: "910GCSEAH", zone: "2" },
  { name: "Island Gardens DLR Station", id: "940GZZDLISL", zone: "2" },
  { name: "Kennington Underground Station", id: "940GZZLUKNG", zone: "2" },
  { name: "Kensal Green Rail Station", id: "910GKENSLG", zone: "2" },
  { name: "Kensal Green Underground Station", id: "940GZZLUKSL", zone: "2" },
  { name: "Kensal Rise Rail Station", id: "910GKENR", zone: "2" },
  { name: "Kensington (Olympia) Rail Station", id: "910GKENOLYM", zone: "2" },
  {
    name: "Kensington (Olympia) Underground Station",
    id: "940GZZLUKOY",
    zone: "2"
  },
  { name: "Kentish Town Underground Station", id: "940GZZLUKSH", zone: "2" },
  { name: "Kentish Town West Rail Station", id: "910GKNTSHTW", zone: "2" },
  { name: "Kenton Rail Station", id: "910GKTON", zone: "4" },
  { name: "Kenton Underground Station", id: "940GZZLUKEN", zone: "4" },
  { name: "Kew Gardens Rail Station", id: "910GKEWGRDN", zone: "3+4" },
  { name: "Kew Gardens Underground Station", id: "940GZZLUKWG", zone: "3+4" },
  { name: "Kilburn High Road Rail Station", id: "910GKLBRNHR", zone: "2" },
  { name: "Kilburn Park Underground Station", id: "940GZZLUKPK", zone: "2" },
  { name: "Kilburn Underground Station", id: "940GZZLUKBN", zone: "2" },
  { name: "King George V DLR Station", id: "940GZZDLKGV", zone: "3" },
  {
    name: "King's Cross St. Pancras Underground Station",
    id: "940GZZLUKSX",
    zone: "1"
  },
  { name: "Kingsbury Underground Station", id: "940GZZLUKBY", zone: "4" },
  { name: "Knightsbridge Underground Station", id: "940GZZLUKNB", zone: "1" },
  { name: "Ladbroke Grove Underground Station", id: "940GZZLULAD", zone: "2" },
  { name: "Lambeth North Underground Station", id: "940GZZLULBN", zone: "1" },
  { name: "Lancaster Gate Underground Station", id: "940GZZLULGT", zone: "1" },
  { name: "Langdon Park DLR Station", id: "940GZZDLLDP", zone: "2" },
  { name: "Latimer Road Underground Station", id: "940GZZLULRD", zone: "2" },
  {
    name: "Leicester Square Underground Station",
    id: "940GZZLULSQ",
    zone: "1"
  },
  { name: "Lewisham DLR Station", id: "940GZZDLLEW", zone: "2+3" },
  { name: "Leyton Midland Road Rail Station", id: "910GLEYTNMR", zone: "3" },
  { name: "Leyton Underground Station", id: "940GZZLULYN", zone: "3" },
  { name: "Leytonstone High Road Rail Station", id: "910GLYTNSHR", zone: "3" },
  { name: "Leytonstone Underground Station", id: "940GZZLULYS", zone: "3+4" },
  { name: "Limehouse DLR Station", id: "940GZZDLLIM", zone: "2" },
  {
    name: "Liverpool Street Underground Station",
    id: "940GZZLULVT",
    zone: "1"
  },
  { name: "London Bridge Underground Station", id: "940GZZLULNB", zone: "1" },
  { name: "London City Airport DLR Station", id: "940GZZDLLCA", zone: "3" },
  { name: "London Euston Rail Station", id: "910GEUSTON", zone: "1" },
  { name: "London Fields Rail Station", id: "910GLONFLDS", zone: "2" },
  { name: "London Liverpool Street Rail Station", id: "910GLIVST", zone: "1" },
  { name: "London Paddington Rail Station", id: "910GPADTON", zone: "1" },
  { name: "Loughton Underground Station", id: "940GZZLULGN", zone: "6" },
  { name: "Maida Vale Underground Station", id: "940GZZLUMVL", zone: "2" },
  { name: "Manor House Underground Station", id: "940GZZLUMRH", zone: "2+3" },
  { name: "Manor Park Rail Station", id: "910GMANRPK", zone: "3+4" },
  { name: "Mansion House Underground Station", id: "940GZZLUMSH", zone: "1" },
  { name: "Marble Arch Underground Station", id: "940GZZLUMBA", zone: "1" },
  { name: "Maryland Rail Station", id: "910GMRYLAND", zone: "3" },
  { name: "Marylebone Underground Station", id: "940GZZLUMYB", zone: "1" },
  { name: "Mile End Underground Station", id: "940GZZLUMED", zone: "2" },
  { name: "Mill Hill East Underground Station", id: "940GZZLUMHL", zone: "4" },
  { name: "Monument Underground Station", id: "940GZZLUMMT", zone: "1" },
  { name: "Moor Park Underground Station", id: "940GZZLUMPK", zone: "6+7" },
  { name: "Moorgate Underground Station", id: "940GZZLUMGT", zone: "1" },
  { name: "Morden Underground Station", id: "940GZZLUMDN", zone: "4" },
  {
    name: "Mornington Crescent Underground Station",
    id: "940GZZLUMTC",
    zone: "2"
  },
  { name: "Mudchute DLR Station", id: "940GZZDLMUD", zone: "2" },
  { name: "Neasden Underground Station", id: "940GZZLUNDN", zone: "3" },
  { name: "New Cross ELL Rail Station", id: "910GNWCRELL", zone: "2" },
  { name: "New Cross Gate Rail Station", id: "910GNEWXGTE", zone: "2" },
  { name: "Newbury Park Underground Station", id: "940GZZLUNBP", zone: "4" },
  { name: "North Acton Underground Station", id: "940GZZLUNAN", zone: "2+3" },
  { name: "North Ealing Underground Station", id: "940GZZLUNEN", zone: "3" },
  {
    name: "North Greenwich Underground Station",
    id: "940GZZLUNGW",
    zone: "2+3"
  },
  { name: "North Harrow Underground Station", id: "940GZZLUNHA", zone: "5" },
  { name: "North Wembley Rail Station", id: "910GNWEMBLY", zone: "4" },
  { name: "North Wembley Underground Station", id: "940GZZLUNWY", zone: "4" },
  { name: "Northfields Underground Station", id: "940GZZLUNFD", zone: "3" },
  { name: "Northolt Underground Station", id: "940GZZLUNHT", zone: "5" },
  { name: "Northwick Park Underground Station", id: "940GZZLUNKP", zone: "4" },
  { name: "Northwood Hills Underground Station", id: "940GZZLUNWH", zone: "6" },
  { name: "Northwood Underground Station", id: "940GZZLUNOW", zone: "6" },
  { name: "Norwood Junction Rail Station", id: "910GNORWDJ", zone: "4" },
  {
    name: "Notting Hill Gate Underground Station",
    id: "940GZZLUNHG",
    zone: "1+2"
  },
  { name: "Oakwood Underground Station", id: "940GZZLUOAK", zone: "5" },
  { name: "Old Street Underground Station", id: "940GZZLUODS", zone: "1" },
  { name: "Osterley Underground Station", id: "940GZZLUOSY", zone: "4" },
  { name: "Oval Underground Station", id: "940GZZLUOVL", zone: "2" },
  { name: "Oxford Circus Underground Station", id: "940GZZLUOXC", zone: "1" },
  { name: "Paddington (H&C Line)-Underground", id: "940GZZLUPAH", zone: "1" },
  { name: "Paddington Underground Station", id: "940GZZLUPAC", zone: "1" },
  { name: "Park Royal Underground Station", id: "940GZZLUPKR", zone: "3" },
  { name: "Parsons Green Underground Station", id: "940GZZLUPSG", zone: "2" },
  { name: "Peckham Rye Rail Station", id: "910GPCKHMRY", zone: "2" },
  { name: "Penge West Rail Station", id: "910GPENEW", zone: "4" },
  { name: "Perivale Underground Station", id: "940GZZLUPVL", zone: "4" },
  {
    name: "Piccadilly Circus Underground Station",
    id: "940GZZLUPCC",
    zone: "1"
  },
  { name: "Pimlico Underground Station", id: "940GZZLUPCO", zone: "1" },
  { name: "Pinner Underground Station", id: "940GZZLUPNR", zone: "5" },
  { name: "Plaistow Underground Station", id: "940GZZLUPLW", zone: "3" },
  { name: "Pontoon Dock DLR Station", id: "940GZZDLPDK", zone: "3" },
  { name: "Poplar DLR Station", id: "940GZZDLPOP", zone: "2" },
  { name: "Preston Road Underground Station", id: "940GZZLUPRD", zone: "4" },
  { name: "Prince Regent DLR Station", id: "940GZZDLPRE", zone: "3" },
  { name: "Pudding Mill Lane DLR Station", id: "940GZZDLPUD", zone: "2+3" },
  { name: "Putney Bridge Underground Station", id: "940GZZLUPYB", zone: "2" },
  { name: "Queen's Park Underground Station", id: "940GZZLUQPS", zone: "2" },
  { name: "Queens Park (London) Rail Station", id: "910GQPRK", zone: "2" },
  { name: "Queens Road Peckham Rail Station", id: "910GPCKHMQD", zone: "2" },
  { name: "Queensbury Underground Station", id: "940GZZLUQBY", zone: "4" },
  { name: "Queensway Underground Station", id: "940GZZLUQWY", zone: "1" },
  {
    name: "Ravenscourt Park Underground Station",
    id: "940GZZLURVP",
    zone: "2"
  },
  { name: "Rayners Lane Underground Station", id: "940GZZLURYL", zone: "5" },
  { name: "Rectory Road Rail Station", id: "910GRCTRYRD", zone: "2" },
  { name: "Redbridge Underground Station", id: "940GZZLURBG", zone: "4" },
  { name: "Regent's Park Underground Station", id: "940GZZLURGP", zone: "1" },
  { name: "Richmond (London) Rail Station", id: "910GRICHMND", zone: "4" },
  { name: "Richmond Underground Station", id: "940GZZLURMD", zone: "4" },
  { name: "Rickmansworth Underground Station", id: "940GZZLURKW", zone: "7" },
  { name: "Roding Valley Underground Station", id: "940GZZLURVY", zone: "4" },
  { name: "Romford Rail Station", id: "910GROMFORD", zone: "6" },
  { name: "Rotherhithe Rail Station", id: "910GRTHERHI", zone: "2" },
  { name: "Royal Albert DLR Station", id: "940GZZDLRAL", zone: "3" },
  { name: "Royal Oak Underground Station", id: "940GZZLURYO", zone: "2" },
  { name: "Royal Victoria DLR Station", id: "940GZZDLRVC", zone: "3" },
  { name: "Ruislip Gardens Underground Station", id: "940GZZLURSG", zone: "5" },
  { name: "Ruislip Manor Underground Station", id: "940GZZLURSM", zone: "6" },
  { name: "Ruislip Underground Station", id: "940GZZLURSP", zone: "6" },
  { name: "Russell Square Underground Station", id: "940GZZLURSQ", zone: "1" },
  { name: "Seven Kings Rail Station", id: "910GSVNKNGS", zone: "4" },
  { name: "Seven Sisters Rail Station", id: "910GSEVNSIS", zone: "3" },
  { name: "Seven Sisters Underground Station", id: "940GZZLUSVS", zone: "3" },
  { name: "Shadwell DLR Station", id: "940GZZDLSHA", zone: "2" },
  { name: "Shadwell Rail Station", id: "910GSHADWEL", zone: "2" },

  {
    name: "Shepherd's Bush (Central) Underground Station",
    id: "940GZZLUSBC",
    zone: "2"
  },
  {
    name: "Shepherd's Bush Market Underground Station",
    id: "940GZZLUSBM",
    zone: "2"
  },
  { name: "Shepherds Bush Rail Station", id: "910GSHPDSB", zone: "2" },
  { name: "Shoreditch High Street Rail Station", id: "910GSHRDHST", zone: "1" },
  { name: "Silver Street Rail Station", id: "910GSIVRST", zone: "4" },
  { name: "Sloane Square Underground Station", id: "940GZZLUSSQ", zone: "1" },
  { name: "Snaresbrook Underground Station", id: "940GZZLUSNB", zone: "4" },
  { name: "South Acton Rail Station", id: "910GSACTON", zone: "3" },
  { name: "South Ealing Underground Station", id: "940GZZLUSEA", zone: "3" },
  { name: "South Hampstead Rail Station", id: "910GSHMPSTD", zone: "2" },
  { name: "South Harrow Underground Station", id: "940GZZLUSHH", zone: "5" },
  {
    name: "South Kensington Underground Station",
    id: "940GZZLUSKS",
    zone: "1"
  },
  { name: "South Kenton Rail Station", id: "910GSKENTON", zone: "4" },
  { name: "South Kenton Underground Station", id: "940GZZLUSKT", zone: "4" },
  { name: "South Quay DLR Station", id: "940GZZDLSOQ", zone: "2" },
  { name: "South Ruislip Underground Station", id: "940GZZLUSRP", zone: "5" },
  { name: "South Tottenham Rail Station", id: "910GSTOTNHM", zone: "3" },
  {
    name: "South Wimbledon Underground Station",
    id: "940GZZLUSWN",
    zone: "3+4"
  },
  { name: "South Woodford Underground Station", id: "940GZZLUSWF", zone: "4" },
  { name: "Southall Rail Station", id: "910GSTHALL", zone: "4" },
  { name: "Southbury Rail Station", id: "910GSBURY", zone: "5" },
  { name: "Southfields Underground Station", id: "940GZZLUSFS", zone: "3" },
  { name: "Southgate Underground Station", id: "940GZZLUSGT", zone: "4" },
  { name: "Southwark Underground Station", id: "940GZZLUSWK", zone: "1" },
  {
    name: "St James Street (London) Rail Station",
    id: "910GSTJMSST",
    zone: "3"
  },
  {
    name: "St. James's Park Underground Station",
    id: "940GZZLUSJP",
    zone: "1"
  },
  { name: "St. John's Wood Underground Station", id: "940GZZLUSJW", zone: "2" },
  { name: "St. Paul's Underground Station", id: "940GZZLUSPU", zone: "1" },
  { name: "Stamford Brook Underground Station", id: "940GZZLUSFB", zone: "2" },
  { name: "Stamford Hill Rail Station", id: "910GSTMFDHL", zone: "3" },
  { name: "Stanmore Underground Station", id: "940GZZLUSTM", zone: "5" },
  { name: "Star Lane DLR Station", id: "940GZZDLSTL", zone: "2+3" },
  { name: "Stepney Green Underground Station", id: "940GZZLUSGN", zone: "2" },
  { name: "Stockwell Underground Station", id: "940GZZLUSKW", zone: "2" },
  { name: "Stoke Newington Rail Station", id: "910GSTKNWNG", zone: "2" },
  { name: "Stonebridge Park Rail Station", id: "910GSTNBGPK", zone: "3" },
  {
    name: "Stonebridge Park Underground Station",
    id: "940GZZLUSGP",
    zone: "3"
  },
  { name: "Stratford (London) Rail Station", id: "910GSTFD", zone: "2+3" },
  { name: "Stratford DLR Station", id: "940GZZDLSTD", zone: "2+3" },
  { name: "Stratford High Street DLR Station", id: "940GZZDLSHS", zone: "2+3" },
  {
    name: "Stratford International DLR Station",
    id: "940GZZDLSIT",
    zone: "2+3"
  },
  { name: "Stratford Underground Station", id: "940GZZLUSTD", zone: "2+3" },
  { name: "Sudbury Hill Underground Station", id: "940GZZLUSUH", zone: "4" },
  { name: "Sudbury Town Underground Station", id: "940GZZLUSUT", zone: "4" },
  { name: "Surrey Quays Rail Station", id: "910GSURREYQ", zone: "2" },
  { name: "Swiss Cottage Underground Station", id: "940GZZLUSWC", zone: "2" },
  { name: "Sydenham Rail Station", id: "910GSYDENHM", zone: "3" },
  { name: "Temple Underground Station", id: "940GZZLUTMP", zone: "1" },
  { name: "Theobalds Grove Rail Station", id: "910GTHBLDSG", zone: "7" },
  { name: "Theydon Bois Underground Station", id: "940GZZLUTHB", zone: "6" },
  { name: "Tooting Bec Underground Station", id: "940GZZLUTBC", zone: "3" },
  {
    name: "Tooting Broadway Underground Station",
    id: "940GZZLUTBY",
    zone: "3"
  },
  {
    name: "Tottenham Court Road Underground Station",
    id: "940GZZLUTCR",
    zone: "1"
  },
  { name: "Tottenham Hale Underground Station", id: "940GZZLUTMH", zone: "3" },
  {
    name: "Totteridge & Whetstone Underground Station",
    id: "940GZZLUTAW",
    zone: "4"
  },
  { name: "Tower Gateway DLR Station", id: "940GZZDLTWG", zone: "1" },
  { name: "Tower Hill Underground Station", id: "940GZZLUTWH", zone: "1" },
  { name: "Tufnell Park Underground Station", id: "940GZZLUTFP", zone: "2" },
  { name: "Turkey Street Rail Station", id: "910GTURKYST", zone: "6" },
  { name: "Turnham Green Underground Station", id: "940GZZLUTNG", zone: "2" },
  { name: "Turnpike Lane Underground Station", id: "940GZZLUTPN", zone: "3" },
  {
    name: "Upminster Bridge Underground Station",
    id: "940GZZLUUPB",
    zone: "6"
  },
  { name: "Upminster Rail Station", id: "910GUPMNSTR", zone: "6" },
  { name: "Upminster Underground Station", id: "940GZZLUUPM", zone: "6" },
  { name: "Upney Underground Station", id: "940GZZLUUPY", zone: "4" },
  { name: "Upper Holloway Rail Station", id: "910GUPRHLWY", zone: "2" },
  { name: "Upton Park Underground Station", id: "940GZZLUUPK", zone: "3" },
  { name: "Uxbridge Underground Station", id: "940GZZLUUXB", zone: "6" },
  { name: "Vauxhall Underground Station", id: "940GZZLUVXL", zone: "1+2" },
  { name: "Victoria Underground Station", id: "940GZZLUVIC", zone: "1" },
  { name: "Walthamstow Central Rail Station", id: "910GWLTWCEN", zone: "3" },
  {
    name: "Walthamstow Central Underground Station",
    id: "940GZZLUWWL",
    zone: "3"
  },
  {
    name: "Walthamstow Queens Road Rail Station",
    id: "910GWLTHQRD",
    zone: "3"
  },
  { name: "Wandsworth Road Rail Station", id: "910GWNDSWRD", zone: "2" },
  { name: "Wanstead Park Rail Station", id: "910GWNSTDPK", zone: "3" },
  { name: "Wanstead Underground Station", id: "940GZZLUWSD", zone: "4" },
  { name: "Wapping Rail Station", id: "910GWAPPING", zone: "2" },
  { name: "Warren Street Underground Station", id: "940GZZLUWRR", zone: "1" },
  { name: "Warwick Avenue Underground Station", id: "940GZZLUWKA", zone: "2" },
  { name: "Waterloo Underground Station", id: "940GZZLUWLO", zone: "1" },
  { name: "Watford High Street Rail Station", id: "910GWATFDHS", zone: "8" },

  { name: "Watford Underground Station", id: "940GZZLUWAF", zone: "7" },
  { name: "Wembley Central Rail Station", id: "910GWMBY", zone: "4" },
  { name: "Wembley Central Underground Station", id: "940GZZLUWYC", zone: "4" },
  { name: "Wembley Park Underground Station", id: "940GZZLUWYP", zone: "4" },
  { name: "West Acton Underground Station", id: "940GZZLUWTA", zone: "3" },
  { name: "West Brompton Rail Station", id: "910GWBRMPTN", zone: "2" },
  { name: "West Brompton Underground Station", id: "940GZZLUWBN", zone: "2" },
  { name: "West Croydon Rail Station", id: "910GWCROYDN", zone: "5" },
  { name: "West Ealing Rail Station", id: "910GWEALING", zone: "3" },
  { name: "West Finchley Underground Station", id: "940GZZLUWFN", zone: "4" },
  { name: "West Ham DLR Station", id: "940GZZDLWHM", zone: "2+3" },
  { name: "West Ham Underground Station", id: "940GZZLUWHM", zone: "2+3" },
  { name: "West Hampstead Rail Station", id: "910GWHMDSTD", zone: "2" },
  { name: "West Hampstead Underground Station", id: "940GZZLUWHP", zone: "2" },
  { name: "West Harrow Underground Station", id: "940GZZLUWHW", zone: "5" },
  { name: "West India Quay DLR Station", id: "940GZZDLWIQ", zone: "2" },
  { name: "West Kensington Underground Station", id: "940GZZLUWKN", zone: "2" },
  { name: "West Ruislip Underground Station", id: "940GZZLUWRP", zone: "6" },
  { name: "West Silvertown DLR Station", id: "940GZZDLWSV", zone: "3" },
  { name: "Westbourne Park Underground Station", id: "940GZZLUWSP", zone: "2" },
  { name: "Westferry DLR Station", id: "940GZZDLWFE", zone: "2" },
  { name: "Westminster Underground Station", id: "940GZZLUWSM", zone: "1" },
  { name: "White City Underground Station", id: "940GZZLUWCY", zone: "2" },
  { name: "White Hart Lane Rail Station", id: "910GWHHRTLA", zone: "3" },
  { name: "Whitechapel Rail Station", id: "910GWCHAPEL", zone: "2" },
  { name: "Whitechapel Underground Station", id: "940GZZLUWPL", zone: "2" },
  {
    name: "Willesden Green Underground Station",
    id: "940GZZLUWIG",
    zone: "2+3"
  },
  { name: "Willesden Junction Rail Station", id: "910GWLSDJHL", zone: "2+3" },
  {
    name: "Willesden Junction Underground Station",
    id: "940GZZLUWJN",
    zone: "2+3"
  },
  { name: "Wimbledon Park Underground Station", id: "940GZZLUWIP", zone: "3" },
  { name: "Wimbledon Underground Station", id: "940GZZLUWIM", zone: "3" },
  { name: "Wood Green Underground Station", id: "940GZZLUWOG", zone: "3" },
  { name: "Wood Lane Underground Station", id: "940GZZLUWLA", zone: "2" },
  { name: "Wood Street Rail Station", id: "910GWDST", zone: "4" },
  { name: "Woodford Underground Station", id: "940GZZLUWOF", zone: "4" },
  { name: "Woodgrange Park Rail Station", id: "910GWDGRNPK", zone: "3+4" },
  { name: "Woodside Park Underground Station", id: "940GZZLUWOP", zone: "4" },
  { name: "Woolwich Arsenal DLR Station", id: "940GZZDLWLA", zone: "4" }
];

export default { stationList };
